### ISSUE TITLE
Build error when installed from pod

### ISSUE THREAD

**Issue by xinaesthete** [256dpi/OSCKit#5]
I'm getting this error in `OSCClient.h`

    'GCDAsyncUdpSocket.h' file not found with <angled> include; use "quotes" instead

Briefly tried changing header search paths, without success. It seems https://github.com/segmentio/analytics-ios/issues/417 addresses a similar concern; perhaps it should be `#import <CocoaAsyncSocket/GCDAsyncUdpSocket.h>` or similar?

**Comment by 256dpi** [comment]
not so easy as it seems, I'm working on it...

**Comment by 256dpi** [comment]
Ok, pushed a new version. Should be fine now.

**Comment by xinaesthete** [comment]
Great, thanks. I had to change the line in my Podfile to force it to use the updated version, but I do now have a successful build.

Cheers!
