### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by jbloit** [256dpi/OSCKit#6]
I had trouble compiling, after running pod install within my project (lots of c++ errors). In case it can help others, I solved the issues by adding  "-lstdc++" to the "other linker flags" field of the build settings. Maybe that's something that can be fixed in the podspec file? (not sure).

**Comment by 256dpi** [comment]
Hi! Thanks for letting me know.

I think I have fixed the problem here:
https://github.com/256dpi/OSCKit/pull/7

Could you give it a try and give me feedback?

**Comment by jbloit** [comment]
Successfully tested. Thanks for the fix!

**Comment by 256dpi** [comment]
Cool!
