### ISSUE TITLE
Getting Started Guide should be updated for ARC

### ISSUE THREAD

**Issue by brassel** [256dpi/OSCKit#8]
Hi Joel,

thanks for your great work on OSCKit!
I just wanted you to know that using ARC your example usage code snippets create some erratic behavior. When writing lines like `OSCClient *client = [[OSCClient alloc] init];` sending messages with that client works only occasionally if the client is not destroyed before sending the message.
Maybe it would be a good idea to write things like `@property (nonatomic, strong) OSCClient *client;` and `self.client = [[OSCClient alloc] init];` into the Readme instead.

Cheers
brassel

**Comment by 256dpi** [comment]
Thanks for reporting this, I updated the readme accordingly.
